### ISSUE TITLE
Ethereum a storage solution

### ISSUE THREAD

**Issue by doronaviguy** [mprimi/portable-secret#11]
Saving encrypted data on public servers is a great idea,
but there is no assurance of data persistency , 
my suggestion is store the data on an Ethereum transaction ( using calldata args) , this way the data will be persistent in the chain forever , and the data will be replicated on thousands of servers in a decentralized manner

**Comment by Kidlike** [comment]
forgive my ignorance, but isn't that _expensive_ (gas fees) ?

**Comment by therealredvoid** [comment]
> Saving encrypted data on public servers is a great idea, but there is no assurance of data persistency , my suggestion is store the data on an Ethereum transaction ( using calldata args) , this way the data will be persistent in the chain forever , and the data will be replicated on thousands of servers in a decentralized manner

I understand your concern but don't you think most people would not be comfortable getting data saved "permanently"?

**Comment by doronaviguy** [comment]
yes 
gas fees cost money , 
but if you schedule your tx when gas fees are low , you can pay couple of dollars and get persistency forever , on the most secure chain 

note - there are cheaper chains then ethereum like polygon or bnb chain where this costs can be reduced to a few cents but ethereum is the most secure and decentralized chain of them all.

ofcourse this solution is suitable only for small documents 

i think the maximum you can store in ethereum tx is 44kb in call data ( just checked quickly, it might be more )

**Comment by mprimi** [comment]
It's your data. Store it wherever you like.

Discussing the pros and cons of using Ethereum as a persistent storage seems out of scope for this project so I'm closing this.
