### ISSUE TITLE
Secret Creator doesn't work from file:// (offline)

### ISSUE THREAD

**Issue by dardoor** [mprimi/portable-secret#14]
If I try to generate a secret using the downloaded index.html file I get a TypeError. Is this normal/expected?

**Comment by mprimi** [comment]
Indeed, in the current form you need to run an HTTPS server locally to use the creator. The README in that folder contains some more details. https://github.com/mprimi/portable-secret/tree/main/creator

**Comment by mprimi** [comment]
See also: https://github.com/mprimi/portable-secret/issues/8
