### ISSUE TITLE
State the encryption algorithms in the README

### ISSUE THREAD

**Issue by shadowbq** [mprimi/portable-secret#27]
I understand keeping the UI clean, but the encryption even though you didn’t write the algorithm you choose the implementation details. AES and keysize with PKCS padding options should be explained in the README because THESE ARE implementation details important to users. 

You’re documenting the html very clearly but I would like to see it outside of the code.

**Comment by mprimi** [comment]
I agree, the README should explain the encryption scheme.

**Comment by mprimi** [comment]
Added a detailed description of encryption & decryption to readme in https://github.com/mprimi/portable-secret/pull/39

See https://mprimi.github.io/portable-secret/#cryptography
